"use server";

import { createClient, createAdminClient } from "@/lib/supabase/server";
import { revalidatePath } from "next/cache";

type ActionResult = { success: boolean; error?: string };

/**
 * Send an invite to a new member. Admin only.
 * Creates a pending_invite row and sends invite email.
 */
export async function sendInvite(formData: FormData): Promise<ActionResult> {
  const supabase = await createClient();
  const {
    data: { user },
  } = await supabase.auth.getUser();
  if (!user) return { success: false, error: "Not authenticated." };

  const { data: profile } = await supabase
    .from("profiles")
    .select("role")
    .eq("id", user.id)
    .single();

  if (profile?.role !== "admin") return { success: false, error: "Admin access required." };

  const email = (formData.get("email") as string)?.toLowerCase().trim();
  if (!email || !email.includes("@")) {
    return { success: false, error: "Invalid email address." };
  }

  // Check if already a member
  const { data: existing } = await supabase
    .from("profiles")
    .select("id")
    .eq("email", email)
    .single();

  if (existing) {
    return { success: false, error: "That email is already a member." };
  }

  // Create invite row (token auto-generated by DB default)
  const { data: invite, error: inviteError } = await supabase
    .from("pending_invites")
    .insert({ email, invited_by: user.id })
    .select("token")
    .single();

  if (inviteError || !invite) {
    return { success: false, error: "Failed to create invite." };
  }

  // Send invite email via Supabase Auth (magic link to the invite acceptance page)
  const adminClient = await createAdminClient();
  const appUrl = process.env.NEXT_PUBLIC_APP_URL ?? "http://localhost:3000";
  const inviteUrl = `${appUrl}/invite?token=${invite.token}`;

  const { error: emailError } = await adminClient.auth.admin.inviteUserByEmail(email, {
    redirectTo: inviteUrl,
    data: { invite_token: invite.token },
  });

  if (emailError) {
    // Clean up the invite row if email fails
    await supabase.from("pending_invites").delete().eq("token", invite.token);
    return { success: false, error: `Failed to send invite email: ${emailError.message}` };
  }

  revalidatePath("/admin/members");
  return { success: true };
}

/**
 * Resend an existing invite (creates a new token, invalidates old one).
 */
export async function resendInvite(invite_id: string): Promise<ActionResult> {
  const supabase = await createClient();
  const {
    data: { user },
  } = await supabase.auth.getUser();
  if (!user) return { success: false, error: "Not authenticated." };

  const { data: profile } = await supabase
    .from("profiles")
    .select("role")
    .eq("id", user.id)
    .single();
  if (profile?.role !== "admin") return { success: false, error: "Admin access required." };

  // Get original invite
  const { data: original } = await supabase
    .from("pending_invites")
    .select("email, invited_by")
    .eq("id", invite_id)
    .single();

  if (!original) return { success: false, error: "Invite not found." };

  // Create a fresh invite
  const formData = new FormData();
  formData.set("email", original.email);

  // Delete old pending invite first
  await supabase.from("pending_invites").delete().eq("id", invite_id);

  return sendInvite(formData);
}

/**
 * Accept an invite. Called from the /invite page.
 * Creates the member profile and generates a magic link for immediate sign-in.
 */
export async function acceptInvite(
  token: string,
  display_name: string
): Promise<ActionResult & { actionLink?: string }> {
  if (!token || !display_name.trim()) {
    return { success: false, error: "Please provide your name." };
  }

  const supabase = await createClient();

  // Validate token
  const { data: tokenCheck } = await supabase.rpc("check_invite_token", { p_token: token });

  if (!tokenCheck?.valid) {
    return {
      success: false,
      error: "This invite link is invalid or has expired. Ask your coordinator to resend it.",
    };
  }

  const email = tokenCheck.email as string;

  // Accept invite and upsert profile with the display_name from the form
  const { data: result } = await supabase.rpc("accept_invite", {
    p_token: token,
    p_display_name: display_name.trim(),
  });

  if (result?.error) {
    return { success: false, error: "Failed to complete signup. Please try again." };
  }

  // Generate a magic link so the user is signed in immediately after the invite form
  const adminClient = await createAdminClient();
  const appUrl = process.env.NEXT_PUBLIC_APP_URL ?? "http://localhost:3000";

  const { data: linkData, error: linkError } = await adminClient.auth.admin.generateLink({
    type: "magiclink",
    email,
    options: { redirectTo: `${appUrl}/auth/callback` },
  });

  if (linkError || !linkData?.properties?.action_link) {
    return { success: false, error: "Account created but sign-in link failed. Try signing in with a magic link." };
  }

  return { success: true, actionLink: linkData.properties.action_link };
}
