"use server";

import { createClient, createAdminClient } from "@/lib/supabase/server";
import { revalidatePath } from "next/cache";

type ActionResult = { success: boolean; error?: string };

/**
 * Send an invite to a new member. Admin only.
 * Creates a pending_invite row and sends invite email.
 */
export async function sendInvite(formData: FormData): Promise<ActionResult> {
  const supabase = await createClient();
  const {
    data: { user },
  } = await supabase.auth.getUser();
  if (!user) return { success: false, error: "Not authenticated." };

  const { data: profile } = await supabase
    .from("profiles")
    .select("role")
    .eq("id", user.id)
    .single();

  if (profile?.role !== "admin") return { success: false, error: "Admin access required." };

  const email = (formData.get("email") as string)?.toLowerCase().trim();
  if (!email || !email.includes("@")) {
    return { success: false, error: "Invalid email address." };
  }

  // Check if already a member
  const { data: existing } = await supabase
    .from("profiles")
    .select("id")
    .eq("email", email)
    .single();

  if (existing) {
    return { success: false, error: "That email is already a member." };
  }

  // Create invite row (token auto-generated by DB default)
  const { data: invite, error: inviteError } = await supabase
    .from("pending_invites")
    .insert({ email, invited_by: user.id })
    .select("token")
    .single();

  if (inviteError || !invite) {
    return { success: false, error: "Failed to create invite." };
  }

  // Send invite email via Supabase Auth (magic link to the invite acceptance page)
  const adminClient = await createAdminClient();
  const appUrl = process.env.NEXT_PUBLIC_APP_URL ?? "http://localhost:3000";
  const inviteUrl = `${appUrl}/invite?token=${invite.token}`;

  // Use Supabase admin to send a custom email (or use inviteUserByEmail as the transport)
  // We send them to our custom /invite page, not Supabase's default flow
  const { error: emailError } = await adminClient.auth.admin.inviteUserByEmail(email, {
    redirectTo: inviteUrl,
    data: { invite_token: invite.token },
  });

  if (emailError) {
    // Clean up the invite row if email fails
    await supabase.from("pending_invites").delete().eq("token", invite.token);
    return { success: false, error: `Failed to send invite email: ${emailError.message}` };
  }

  revalidatePath("/admin/members");
  return { success: true };
}

/**
 * Resend an existing invite (creates a new token, invalidates old one).
 */
export async function resendInvite(invite_id: string): Promise<ActionResult> {
  const supabase = await createClient();
  const {
    data: { user },
  } = await supabase.auth.getUser();
  if (!user) return { success: false, error: "Not authenticated." };

  const { data: profile } = await supabase
    .from("profiles")
    .select("role")
    .eq("id", user.id)
    .single();
  if (profile?.role !== "admin") return { success: false, error: "Admin access required." };

  // Get original invite
  const { data: original } = await supabase
    .from("pending_invites")
    .select("email, invited_by")
    .eq("id", invite_id)
    .single();

  if (!original) return { success: false, error: "Invite not found." };

  // Create a fresh invite
  const formData = new FormData();
  formData.set("email", original.email);

  // Delete old pending invite first
  await supabase.from("pending_invites").delete().eq("id", invite_id);

  return sendInvite(formData);
}

/**
 * Accept an invite. Called from the /invite page.
 * Unauthenticated context — uses service role via RPC.
 */
export async function acceptInvite(
  token: string,
  display_name: string,
  password: string
): Promise<ActionResult & { email?: string }> {
  if (!token || !display_name.trim() || !password || password.length < 8) {
    return { success: false, error: "Please provide your name and a password (8+ characters)." };
  }

  const supabase = await createClient();

  // Validate token first
  const { data: tokenCheck } = await supabase.rpc("check_invite_token", { p_token: token });

  if (!tokenCheck?.valid) {
    return {
      success: false,
      error: "This invite link is invalid or has expired. Ask your coordinator to resend it.",
    };
  }

  const email = tokenCheck.email as string;

  // Create the auth user with the provided password
  const adminClient = await createAdminClient();
  const { data: authData, error: authError } = await adminClient.auth.admin.createUser({
    email,
    password,
    email_confirm: true,
    user_metadata: { display_name },
  });

  if (authError) {
    // User might already exist (e.g. Supabase invite already created them)
    if (!authError.message.includes("already been registered")) {
      return { success: false, error: `Account creation failed: ${authError.message}` };
    }
  }

  // Accept the invite and create profile
  const { data: result } = await supabase.rpc("accept_invite", {
    p_token: token,
    p_display_name: display_name.trim(),
  });

  if (result?.error) {
    return { success: false, error: "Failed to complete signup. Please try again." };
  }

  return { success: true, email };
}
